apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://openbao.example.com
      caProvider:
        type: ConfigMap
        name: openbao-ca
        key: ca.crt
        namespace: external-secrets
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-development 
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

