apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-winwithcherwin-com
  namespace: ingress-nginx
spec:
  secretName: wildcard-winwithcherwin-com
  dnsNames:
    - "*.staging.winwithcherwin.com"
    - staging.winwithcherwin.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer

