apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-winwithcherwin-com
  namespace: ingress-nginx
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "open-webui,localhost,oblivion,k8sgpt-operator-system"
  secretName: wildcard-winwithcherwin-com
  dnsNames:
    - "*.lab.winwithcherwin.com"
    - lab.winwithcherwin.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer

