apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      ingressClass: nginx
      hostNetwork: true
      daemonset:
        useHostPort: true
      service:
        type: ClusterIP
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: winwithcherwin.com
        external-dns.alpha.kubernetes.io/target: 138.199.163.162
