apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: external-dns
  namespace: external-dns
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-development

  # path of the secret
  path: apps/external-dns/digitalocean

  # dest k8s secret
  destination:
    name: digitalocean-dns
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: external-dns

