- name: Configure WireGuard
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure package index is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install WireGuard
      apt:
        name: wireguard
        state: present
  handlers:
    - name: Restart WireGuard
      systemd:
        name: wg-quick@wg0
        state: restarted
        enabled: true

