- name: Configure WireGuard
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Write wg0.conf
      copy:
        dest: /etc/wireguard/wg0.conf
        content: "{{ wireguard_config }}"
        owner: root
        group: root
        mode: '0600'

    - name: Restart wireguard
      systemd:
        name: wg-quick@wg0
        state: restarted

