- name: Enable WireGuard
  hosts: all
  gather_facts: false

  tasks:
    - name: Check if wg0 interface exists
      command: ip link show wg0
      register: wg0_status
      failed_when: false
      changed_when: false

    - name: Bring up wg0 if not already up
      command: wg-quick up wg0
      when: wg0_status.rc != 0

    - name: Enable WireGuard interface at boot
      systemd:
        name: wg-quick@wg0
        enabled: true

