- name: Set /etc/hosts for all WireGuard nodes
  hosts: all
  gather_facts: false

  vars:
    dest_path: "/etc/hosts"

  tasks:
    - name: Generate wireguard host data
      run_once: true
      delegate_to: localhost
      set_fact:
        wireguard_hosts: "{{ lookup('pipe', 'python3 scripts/generate_hosts.py') | from_json }}"

    - name: Debug wireguard_hosts
      debug:
        var: wireguard_hosts

    - name: Set peer list and hostname for this host
      set_fact:
        peers: "{{ wireguard_hosts[inventory_hostname]['peers'] }}"
        hostname: "{{ wireguard_hosts[inventory_hostname]['hostname'] }}"

    - name: Push /etc/hosts to remote hosts
      ansible.builtin.copy:
        content: "{{ lookup('template', 'templates/hosts.j2') }}"
        dest: "{{ dest_path }}"
        owner: root
        group: root
        mode: '0644'

