apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane          # <- CAPI flavoured CRD
metadata:
  name: do-lab
  namespace: oblivion
spec:
  replicas: 1
  version: v1.29.1+k0s.0             # <-- pick any k0s you like
  persistence:
    type: emptyDir                   # demo – no HA ETCD/Kine
  service:                           # expose the API so the Droplet can see it
    type: ClusterIP
    apiPort: 6443
