---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: do-lab-droplet
  namespace: oblivion
spec:
  address: 178.128.252.101
  port: 22
  user: root
  sshKeyRef:
    name: oblivion-ssh-key
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: do-lab
  namespace: oblivion        # ← same ns & name as the K0smotronControlPlane
spec:
  controlPlaneEndpoint:
    host: 91.99.2.195
    port: 30443
  clusterNetwork:
    pods:       { cidrBlocks: ["192.168.0.0/16"] }
    services:   { cidrBlocks: ["10.128.0.0/12"] }
    serviceDomain: cluster.local
  controlPlaneRef:           # tell CAPI which CP object is ours
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: do-lab
  infrastructureRef:         # a no‑op placeholder that satisfies the CAPI contract
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: do-lab
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane          # <- CAPI flavoured CRD
metadata:
  name: do-lab
  namespace: oblivion
spec:
  version: v1.30.4-k0s.0
  externalAddress: 91.99.2.195
  etcd:
    autoDeletePVCs: true
  persistence:
    autoDeletePVCs: true
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    spec:
      api:
        externalAddress: 91.99.2.195
        sans:
          - 10.8.0.4
          - 91.99.2.195
      network:
        provider: kuberouter
        podCIDR: "192.168.0.0/16"
        serviceCIDR: "10.128.0.0/12"
        kuberouter:
          ipMasq: true
          extraArgs:
            enable-cni: "true"
            run-service-proxy: "true"
            enable-pod-egress: "true"
        kubeProxy:
          disabled: true
  replicas: 1
  service:                           # expose the API so the Droplet can see it
    type: NodePort
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteCluster
metadata:
  name: do-lab
  namespace: oblivion
spec:
  controlPlaneEndpoint:
    host: 91.99.2.195
    port: 30443
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: do-lab-droplet
  namespace: oblivion
spec:
  version: v1.30.4+k0s.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: do-lab-droplet
  namespace: oblivion
spec:
  clusterName: do-lab
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: do-lab-droplet
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: do-lab-droplet
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oblivion-ssh-key
  namespace: oblivion
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-staging

  # path of the secret
  path: apps/oblivion/ssh

  # dest k8s secret
  destination:
    name: oblivion-ssh-key
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: oblivion
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: oblivion
  namespace: oblivion
spec:
  method: kubernetes
  mount: kubernetes-staging
  kubernetes:
    role: vault-secrets-operator-controller-manager
    serviceAccount: default
    audiences:
      - vault