apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane          # <- CAPI flavoured CRD
metadata:
  name: do-lab
  namespace: oblivion
spec:
  replicas: 1
  version: v1.32.4-k0s.0             # <-- pick any k0s you like
  persistence:
    type: emptyDir                   # demo – no HA ETCD/Kine
  service:                           # expose the API so the Droplet can see it
    type: ClusterIP
    apiPort: 6443
---
# cluster-do-lab.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: do-lab
  namespace: oblivion        # ← same ns & name as the K0smotronControlPlane
spec:
  clusterNetwork:
    pods:       { cidrBlocks: ["192.168.0.0/16"] }
    services:   { cidrBlocks: ["10.128.0.0/12"] }
    serviceDomain: cluster.local
  controlPlaneRef:           # tell CAPI which CP object is ours
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: do-lab
  infrastructureRef:         # a no‑op placeholder that satisfies the CAPI contract
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: do-lab
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteCluster
metadata:
  name: do-lab
  namespace: oblivion
spec:
  controlPlaneEndpoint:
    host: k8s.example.com
    port: 6443
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oblivion-ssh-key
  namespace: oblivion
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-staging

  # path of the secret
  path: apps/oblivion/ssh

  # dest k8s secret
  destination:
    name: oblivion-ssh-key
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: oblivion
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: oblivion
  namespace: oblivion
spec:
  method: kubernetes
  mount: kubernetes-staging
  kubernetes:
    role: vault-secrets-operator-controller-manager
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: do-lab-droplet
  namespace: oblivion
spec:
  address: 161.35.95.60
  port: 22
  user: root
  sshKeyRef:
    name: oblivion-ssh-key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: do-lab-droplet
  namespace: oblivion
spec:
  version: v1.32.4+k0s.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: do-lab-droplet
  namespace: oblivion
spec:
  clusterName: do-lab
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: do-lab-droplet
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: do-lab-droplet