apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-staging
  namespace: oblivion
spec:
  instances: 1
  imageName: winwithcherwin/pgvector:15.12-13

  bootstrap:
    initdb:
      database: app
      postInitApplicationSQL:
        - "CREATE EXTENSION \"uuid-ossp\";"
        - "CREATE EXTENSION vector;"
        - "CREATE EXTENSION pg_trgm;"
        - "CREATE EXTENSION fuzzystrmatch;"
  storage:
    size: 5Gi
