apiVersion: droplet.digitalocean.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: demo-droplet
spec:
  forProvider:
    name: demo-droplet
    region: ams3
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
    sshKeys:
      - "d8:57:d3:22:fc:e8:98:0c:d7:64:07:bd:0e:28:f2:84"
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    namespace: oblivion
    name: demo-droplet-conn
