---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sgpt-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8sgpt
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.k8sgpt.ai/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: k8sgpt-operator
      sourceRef:
        kind: HelmRepository
        name: k8sgpt
        namespace: flux-system
  values:
    controllerManager:
      manager:
        image:
          repository: winwithcherwin/k8sgpt-operator-mcp
          tag: latest
          pullPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8sgpt-mcpo
  namespace: k8sgpt-operator-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - secretName: wildcard-winwithcherwin-com
      hosts:
        - "*.staging.winwithcherwin.com"
  rules:
    - host: cc96231f-2914-4a6e-b369-6173f5a3fd0e.staging.winwithcherwin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8sgpt
                port:
                  number: 8000

