apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    backend: openai
    model: gpt-4o-mini
    secret:
      name: openai
      key: token
  noCache: false
  repository: winwithcherwin/k8sgpt-mcpo
  version: latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
  namespace: k8sgpt-operator-system
data:
  config.json: |
    {
      "mcpServers": {
        "k8sgpt": {
          "command": "/k8sgpt",
          "args": ["serve", "--mcp"]
        },
        "git": {
          "command": "mcp-server-git",
          "args": ["--repository", "/workspace", "-v", "-v"]
        }
      }
    }