---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sgpt-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8sgpt
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.k8sgpt.ai/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: k8sgpt-operator
      sourceRef:
        kind: HelmRepository
        name: k8sgpt
        namespace: flux-system
---
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    backend: openai
    model: gpt-4o-mini
    secret:
      name: openai
      key: token
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.17