---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-capi-resources-for-droplet
spec:
  background: true
  rules:
  - name: generate-remote-machine-for-droplet
    context:
      - name: remoteMachineAddress
        apiCall:
          urlPath: "/apis/infrastructure.cluster.x-k8s.io/v1beta1/namespaces/oblivion/remotemachines/{{ request.object.metadata.name }}"
          jmesPath: "spec.address"
          default: ""
    match:
      any:
      - resources:
          kinds:
          - Droplet
    preconditions:
      all:
      - key: "{{ request.object.status.atProvider.ipv4Address }}"
        operator: NotEquals
        value: ""
      - key: "{{ request.object.status.atProvider.ipv4Address }}"
        operator: NotEquals
        value: "{{ remoteMachineAddress }}"
    generate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: RemoteMachine
      name: "{{ request.object.metadata.name }}"
      namespace: oblivion
      synchronize: true
      generateExisting: true
      data:
        spec:
          address: "{{ request.object.status.atProvider.ipv4Address }}"
          port: 22
          user: root
          sshKeyRef:
            name: oblivion-ssh-key
  - name: generate-k0sworker-config
    match:
      any:
      - resources:
          kinds:
          - Droplet
    generate:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: "{{ request.object.metadata.name }}"
      namespace: oblivion
      synchronize: true
      generateExisting: true
      data:
        spec:
          version: v1.30.4+k0s.0
  - name: generate-machine
    match:
      any:
      - resources:
          kinds:
          - Droplet
    generate:
      apiVersion: cluster.x-k8s.io/v1beta1
      kind: Machine
      name: "{{ request.object.metadata.name }}"
      namespace: oblivion
      synchronize: true
      generateExisting: true
      data:
        spec:
          clusterName: do-lab
          bootstrap:
            configRef:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: K0sWorkerConfig
              name: "{{ request.object.metadata.name }}"
          infrastructureRef:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: RemoteMachine
            name: "{{ request.object.metadata.name }}"
