apiVersion: v1
kind: ServiceAccount
metadata:
  name: r2r
  namespace: oblivion
---
apiVersion: v1
kind: Service
metadata:
  name: r2r
  namespace: oblivion
spec:
  selector:
    app: r2r
  ports:
    - protocol: TCP
      port: 7272
      targetPort: 7272
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r2r-config 
  namespace: oblivion
data:
  r2r.toml: |
    [database]
    disable_create_extension = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r2r
  namespace: oblivion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r2r
  template:
    metadata:
      labels:
        app: r2r
    spec:
      serviceAccountName: r2r
      restartPolicy: Always
      containers:
        - name: controller
          image: winwithcherwin/r2r:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7272
          livenessProbe:
            httpGet:
              path: /v3/health
              port: http
          command:
            - python3
            - -m
            - r2r.serve
          volumeMounts:
            - name: r2r-config-volume
              mountPath: /etc/r2r
              readOnly: true
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: token
            - name: R2R_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: user
            - name: R2R_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: password
            - name: R2R_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: host
            - name: R2R_POSTGRES_PORT
              value: "5432"
            - name: R2R_POSTGRES_DBNAME
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: dbname
            - name: R2R_POSTGRES_NAME
              value: oblivion
            - name: R2R_CONFIG_PATH
              value: /etc/r2r/r2r.toml
            - name: R2R_PORT
              value: "7272"
      volumes:
        - name: r2r-config-volume
          configMap:
            name: r2r-config

