apiVersion: v1
kind: ServiceAccount
metadata:
  name: r2r
  namespace: oblivion
---
apiVersion: v1
kind: Service
metadata:
  name: r2r
  namespace: oblivion
spec:
  selector:
    app: r2r
  ports:
    - protocol: TCP
      name: server
      port: 7272
      targetPort: 7272
    - protocol: TCP
      name: hatchet
      port: 7274
      targetPort: 7274
---
apiVersion: v1
kind: Service
metadata:
  name: r2r-dashboard
  namespace: oblivion
spec:
  selector:
    app: r2r
  ports:
    - protocol: TCP
      name: http
      port: 7273
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r2r-config 
  namespace: oblivion
data:
  r2r.toml: |
    [database]
    disable_create_extension = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r2r
  namespace: oblivion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r2r
  template:
    metadata:
      labels:
        app: r2r
    spec:
      serviceAccountName: r2r
      restartPolicy: Always
      containers:
        - name: dashboard
          image: sciphiai/r2r-dashboard:1.0.3
          env:
            - name: NEXT_PUBLIC_R2R_DEPLOYMENT_URL
              value: "http://r2r:7272"
            - name: NEXT_PUBLIC_HATCHET_DASHBOARD_URL
              value: "http://r2r:7274"
            - name: NEXT_PUBLIC_R2R_DEFAULT_EMAIL
              value: "admin@example.com"
            - name: NEXT_PUBLIC_R2R_DEFAULT_PASSWORD
              value: "Admin123!!"
        - name: server
          image: sciphiai/r2r:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7272
          livenessProbe:
            httpGet:
              path: /v3/health
              port: http
          command:
            - python3
            - -m
            - r2r.serve
          volumeMounts:
            - name: r2r-config-volume
              mountPath: /etc/r2r
              readOnly: true
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: token
            - name: R2R_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: user
            - name: R2R_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: password
            - name: R2R_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: host
            - name: R2R_POSTGRES_PORT
              value: "5432"
            - name: R2R_POSTGRES_DBNAME
              valueFrom:
                secretKeyRef:
                  name: db-staging-app
                  key: dbname
            - name: R2R_POSTGRES_NAME
              value: oblivion
            - name: R2R_CONFIG_PATH
              value: /etc/r2r/r2r.toml
            - name: R2R_PORT
              value: "7272"
      volumes:
        - name: r2r-config-volume
          configMap:
            name: r2r-config

