---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kubernetes-create-control-plane
spec:
  background: true
  rules:
  - name: create-control-plane
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          annotations:
            create-cluster/enable: "true"
          selector:
            matchLabels:
              provider: digitalocean
    context:
    - name: config
      configMap:
        name: "{{ request.object.metadata.name }}"
        namespace: "{{ request.namespace }}"
    - name: context
      variable:
        jmesPath: "config.data.context | parse_yaml(@)"   
    generate:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: K0smotronControlPlane
      name: "{{ context.clusterName }}"
      namespace: "{{ request.namespace }}"
      generateExisting: true
      data:
        spec:
          version: v1.30.4-k0s.0
          externalAddress: "{{ context.controlPlaneEndpoint.host }}"
          etcd:
            autoDeletePVCs: true
          persistence:
            autoDeletePVCs: true
          k0sConfig:
            apiVersion: k0s.k0sproject.io/v1beta1
            kind: ClusterConfig
            spec:
              extensions:
                helm:
                  concurrenyLevel: 5
                  repositories:
                    - name: jetstack
                      url: https://charts.jetstack.io
                    - name: ingress-nginx
                      url: https://kubernetes.github.io/ingress-nginx
                  charts:
                    - name: cert-manager
                      repository: jetstack
                      namespace: cert-manager
                      values:
                        installCRDs: true
                        serviceAccount:
                          create: true
                          name: cert-manager
                    - name: ingress-nginx
                      repository: ingress-nginx
                      namespace: ingress-nginx
                      values:
                        controller:
                          ingressClassResource:
                            name: nginx
                            enabled: true
                            default: true
                          ingressClass: nginx
                          hostNetwork: true
                          daemonset:
                            useHostPort: true
                          service:
                            type: ClusterIP
              api:
                externalAddress: "{{ context.controlPlaneEndpoint.host }}"
              network:
                provider: kuberouter
                kuberouter:
                  ipMasq: true
          replicas: 1
          service:
            type: NodePort
            apiPort: "{{ context.controlPlaneEndpoint.port }}"
            konnectivityPort: "{{ context.konnectivityPort }}"