apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-demo-cluster
  namespace: demo
  labels:
    provider: digitalocean
  annotations:
    create-cluster/enable: "true"
data:
  context: |
    clusterName: "demo-cluster"
    nodeCount: 1
    instanceType: "s-1vcpu-1gb"
    controlPlaneEndpoint:
      host: "91.99.2.195"
      port: 30443