apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: bootstrap-kubernetes-worker-droplet
spec:
  background: true
  rules:
  - name: create-droplet
    match:
      any:
      - resources:
          kinds:
          - Sensor
          annotations:
            create-remote-machine: "true"
          selector:
            matchLabels:
              provider: digitalocean
    context:
    - name: config
      configMap:
        name: "{{ request.object.metadata.labels.owner }}"
        namespace: "{{ request.namespace }}"
    - name: context
      variable:
        jmesPath: "config.data.context | parse_yaml(@)"              
    generate:
      apiVersion: droplet.digitalocean.crossplane.io/v1alpha1
      kind: Droplet
      name: "{{ context.clusterName }}-droplet"
      generateExisting: true
      data:
        metadata: 
          labels:
            namespace: "{{ request.namespace }}"
        spec:
          forProvider:
            name: "{{ context.clusterName }}-droplet"
            region: "ams3"
            size: "{{ context.instanceType }}"
            image: "ubuntu-22-04-x64"
            sshKeys: ["{{ context.sshKeyId }}"]
            providerConfigRef:
              name: "default"
