apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: create-event-trigger
spec:
  background: true
  rules:
  - name: create-event-bus
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          annotations:
            create-cluster/enable: "true"
          selector:
            matchLabels:
              provider: digitalocean
    context:
    - name: config
      configMap:
        name: "{{ request.object.metadata.name }}"
        namespace: "{{ request.namespace }}"
    - name: context
      variable:
        jmesPath: "config.data.context | parse_yaml(@)"              
    generate:
      apiVersion: argoproj.io/v1alpha1
      kind: EventBus
      name: default
      namespace: "{{ request.namespace }}"
      generateExisting: true
      data:
        spec:
          nats:
            native:
              replicas: 1
  - name: create-bootstrap-droplet-event-source
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          annotations:
            create-cluster/enable: "true"
          selector:
            matchLabels:
              provider: digitalocean
    context:
    - name: config
      configMap:
        name: "{{ request.object.metadata.name }}"
        namespace: "{{ request.namespace }}"
    - name: context
      variable:
        jmesPath: "config.data.context | parse_yaml(@)"              
    generate:
      apiVersion: argoproj.io/v1alpha1
      kind: EventSource
      name: droplet-update
      namespace: "{{ request.namespace }}"
      generateExisting: true
      data:
        spec:
          resource:
            droplet-update:
              version: v1alpha1
              group: droplet.digitalocean.crossplane.io
              resource: droplets
              eventTypes: [UPDATE]
              filter:
                labels:
                  - key: namespace
                    operation: "=="
                    value: "{{ request.namespace }}"
  - name: create-watch-droplet-status-sensor
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          annotations:
            create-cluster/enable: "true"
          selector:
            matchLabels:
              provider: digitalocean
    context:
    - name: config
      configMap:
        name: "{{ request.object.metadata.name }}"
        namespace: "{{ request.namespace }}"
    - name: context
      variable:
        jmesPath: "config.data.context | parse_yaml(@)"   
    generate:
      apiVersion: argoproj.io/v1alpha1
      kind: Sensor
      name: "watch-{{ context.clusterName }}-droplet-status"
      namespace: "{{ request.namespace }}"
      generateExisting: true
      data:
        metadata:
          annotations:
            create-remote-machine: "true"
          labels:
            owner: "{{ request.object.metadata.name }}"
            provider: digitalocean
            cluster: "{{ context.clusterName }}"
        spec:
          dependencies:
            - name: droplet-ipv4address-available
              eventSourceName: droplet-update
              eventName: droplet-update
              filters:
                script: |-
                  if event.body.status
                    and event.body.status.atProvider
                    and event.body.status.atProvider.ipv4Address
                    and event.body.status.atProvider.ipv4Address ~= ""
                    and not event.body.metadata.deletionTimestamp
                  then
                    return true
                  else
                    return false
                  end
          triggers:
            - template:
                name: create-droplet-ipv4address-configmap
                k8s:
                  operation: create
                  dest: operation
                  parameters:
                  - src:
                      dependencyName: droplet-ipv4address-available
                      dataKey: body.status.atProvider.ipv4Address
                    dest: data.ipv4Address
                  source:
                    resource:
                      apiVersion: v1
                      kind: ConfigMap
                      metadata:
                        name: "{{ context.clusterName }}-machine"
                        namespace: "{{ request.namespace }}"
                        annotations:
                          create-remote-machine: "true"
                      data:
                        ipv4Address: __WILL_BE_REPLACED__
                        clusterName: "{{ context.clusterName }}"