apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - demo-cm.yaml
  - rbac.yaml
  - controlplane.yaml
  - cluster.yaml
  - events.yaml
  - secrets.yaml
  - droplet.yaml
  - infrastructure.yaml
