apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-ssh-key
spec:
  rules:
  - name: sync-ssh-key
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - kube-system
    generate:
      apiVersion: v1
      kind: Secret
      name: oblivion-ssh-key
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      generateExisting: true
      clone:
        namespace: oblivion
        name: oblivion-ssh-key
