apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: argo-events
  name: configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["list", "watch", "create", "update", "delete"]
  - apiGroups: ["droplet.digitalocean.crossplane.io"]
    resources: ["droplets"]
    verbs: ["list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-reader-binding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: droplet-event-source
  namespace: argo-events
spec:
  resource:
    droplet-update:
      version: v1alpha1
      group: droplet.digitalocean.crossplane.io
      resource: droplets  # Watch the 'pods' resource
      eventTypes: [UPDATE]  # Listen for 'UPDATE' events (Pod status changes)
      #filter:
      #  fields:
      #    - key: status.atProvider.ipv4Address  # Example of filtering for Pod status change
      #      operation: "!="
      #      value: ""  # Only trigger when Pod status is "Running"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: droplet-update-sensor
  namespace: argo-events  # The namespace where the Sensor is created
spec:
  dependencies:
    - name: droplet-update-dependency
      eventSourceName: droplet-event-source  # Name of the EventSource
      eventName: droplet-update  # The event triggered by the EventSource
      transform:
        jq: '.operation += if .type == "ADD" then "create" else if .type == "DELETE" then "delete" else "update" end end'
  triggers:
    - parameters:
      - src:
          dependencyName: droplet-update-dependency
          dataKey: operation
        dest: k8s.operation
      template:
        name: create-configmap
        k8s:
          operation: create
          parameters:
          - src:
              dependencyName: droplet-update-dependency
              dataKey: body.status.atProvider.ipv4Address
            dest: data.ipv4Address
          source: configmaps
            resource:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: droplet-ip-address
                namespace: argo-events
              data:
                ipv4Address: __WILL_BE_REPLACED__
