apiVersion: v1
kind: Pod
metadata:
  name: ubuild
spec:
  restartPolicy: OnFailure
  containers:
  - name: ubuild
    image: registry.registry.svc.cluster.local:5000/oblivion:latest
    imagePullPolicy: Always
    command:
    - python3
    - -m
    - oblivion
    - start
    - ubuild

