apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: external-secrets
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: "0.15.1"

