- name: Creating OpenBao server
  hosts: all
  tasks:
  - name: Get WireGuard details in JSON
    command: ip -j addr show wg0
    register: wg_json
    changed_when: false

  - name: Extract WireGuard IPv4 address
    set_fact:
      wireguard_ip: >-
        {{
          (wg_json.stdout | from_json)[0].addr_info
          | selectattr('family', 'equalto', 'inet')
          | map(attribute='local')
          | list
          | first
        }}

  - name: Debug WireGuard IP
    debug:
      msg: "WireGuard IP is {{ wireguard_ip }}"

  - name: Download OpenBao deb package
    get_url:
      url: https://github.com/openbao/openbao/releases/download/v2.2.0/bao_2.2.0_linux_amd64.deb
      dest: /tmp

  - name: Download GPG signature
    get_url:
      url: https://github.com/openbao/openbao/releases/download/v2.2.0/bao_2.2.0_linux_amd64.deb.gpgsig
      dest: /tmp

  - name: Get GPG public key
    get_url:
      url: https://openbao.org/assets/openbao-gpg-pub-20240618.asc
      dest: /tmp

  - name: Import GPG signature
    command: gpg2 --import /tmp/openbao-gpg-pub-20240618.asc

  - name: Verify GPG signature
    command: gpg2 --verify /tmp/bao_2.2.0_linux_amd64.deb.gpgsig /tmp/bao_2.2.0_linux_amd64.deb

  - name: Install from OpenBao (with APT)
    apt:
      deb: /tmp/bao_2.2.0_linux_amd64.deb

  - name: Configure OpenBao
    template:
      src: templates/openbao.hcl.j2
      dest: /etc/openbao/openbao.hcl
      owner: openbao
      group: openbao
    notify: Restart OpenBao

  handlers:
    - name: Restart OpenBao
      service:
        name: openbao
        state: restarted

