apiVersion: batch/v1
kind: CronJob
metadata:
  name: bao-update-kubernetes-backend
  namespace: oblivion
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: token-reviewer
          containers:
          - name: shell
            image: python:3.12.3
            imagePullPolicy: IfNotPresent
            env:
              - name: PYTHONPATH
                value: /opt/oblivion
            volumeMounts:
              - name: oblivion-source
                mountPath: /opt/oblivion
                readOnly: true
              - name: oblivion-venv
                mountPath: /opt/oblivion-venv
                readOnly: true
            command:
            - /opt/oblivion-venv/bin/python
            - -m
            - oblivion
            - bao
            - update-kubernetes-backend
            - --vault-addres=https://10.8.0.3:8200
            - --cluster-name=development
            - --kube-host=https://10.8.0.4:6443

          volumes:
            - name: oblivion-source
              hostPath:
                path: /opt/oblivion
                type: Directory
            - name: oblivion-venv
              hostPath:
                path: /opt/oblivion-venv
                type: Directory


          

