apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: registry-auth
  namespace: kube-system
spec:
  type: kv-v2
  mount: kubernetes-staging
  path: apps/kube-system/registry
  vaultAuthRef: kube-system
  destination:
    type: kubernetes.io/dockerconfigjson
    name: docker-pull-secret
    create: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "oblivion,kpack"
    transformation:
      excludeRaw: true
      templates:
        ".dockerconfigjson":
          text: |
            {{- $server := (get .Secrets "server") -}}
            {{- $username := (get .Secrets "username") -}}
            {{- $password := (get .Secrets "password") -}}
            {{- $config := dict $server (
              dict
                "username" $username
                "password" $password
                "auth" (list $username $password | join ":" | b64enc)
            )
            -}}
            {{- dict "auths" $config | mustToJson -}}

