apiVersion: ubuild.winwithcherwin.com/v1alpha1
kind: ImageBuild
metadata:
  name: oblivion
  namespace: oblivion
spec:
  image:
    name: registry.registry.svc.cluster.local:5000/oblivion
    secretRef: docker-pull-secret
  git:
    url: github.com/winwithcherwin/oblivion
    revision: main
    triggerPaths:
      - oblivion/
  webhook:
    type: github
    enabled: false
    ingressRef: ubuild-ingress
    secretRef:
      name: docker-pull-secret
      key: password

