apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagebuilds.ubuild.winwithcherwin.com
spec:
  group: ubuild.winwithcherwin.com
  scope: Namespaced
  names:
    plural: imagebuilds
    singular: imagebuild
    kind: ImageBuild
    shortNames:
      - ibld
      - ubuild
      - ubu
      - ub
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [git, image]
              properties:
                git:
                  type: object
                  required: [url]
                  properties:
                    url:
                      type: string
                    revision:
                      type: string
                      default: main
                    contextDir:
                      type: string
                      default: ./
                    dockerfile:
                      type: string
                      default: Dockerfile
                image:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                secretRef:
                  type: string
            status:
              type: object
              properties:
                lastCommit:
                  type: string
                lastBuildTime:
                  type: string
                  format: date-time
                lastImage:
                  type: string
                buildPhase:
                  type: string
                  enum: [Pending, Building, Succeeded, Failed]
                recentLogs:
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
        - name: Git
          type: string
          jsonPath: .spec.git.url
        - name: Revision
          type: string
          jsonPath: .spec.git.revision
        - name: Image
          type: string
          jsonPath: .spec.image.name
        - name: Last Commit
          type: string
          jsonPath: .status.lastCommit
        - name: Phase
          type: string
          jsonPath: .status.buildPhase
        - name: Last Build
          type: date
          jsonPath: .status.lastBuildTime

