apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: registry-auth
  namespace: kube-system
spec:
  type: kv-v2
  mount: kubernetes-staging
  path: apps/kube-system/registry
  vaultAuthRef: kube-system
  destination:
    name: registry-auth
    create: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflect-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflect-allowed-namespaces: "*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "oblivion,kpack"
    transformation:
      templates:
        dockerconfigjson:
          text: |
            {
              "auths": {
                "{{ .server }}": {
                  "username": "{{ .username }}",
                  "password": "{{ .password }}",
                  "email": "{{ .email }}",
                  "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
                }
              }
            }

