---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: oblivion
  namespace: flux-system
spec:
  image: registry.registry.svc.cluster.local:5000/oblivion
  interval: 5m0s
