apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubuild
  namespace: oblivion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ubuild-controller
rules:
  - apiGroups: ["ubuild.winwithcherwin.com"]
    resources: ["imagebuilds"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["ubuild.winwithcherwin.com"]
    resources: ["imagebuilds/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ubuild-builder
  namespace: oblivion
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ubuild-controller
subjects:
  - kind: ServiceAccount
    name: ubuild
    namespace: oblivion
roleRef:
  kind: ClusterRole
  name: ubuild-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ubuild-builder
  namespace: oblivion
subjects:
  - kind: ServiceAccount
    name: ubuild
    namespace: oblivion
roleRef:
  kind: Role
  name: ubuild-builder
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuild
  namespace: oblivion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuild
  template:
    metadata:
      labels:
        app: ubuild
    spec:
      serviceAccountName: ubuild
      restartPolicy: Always
      containers:
        - name: controller
          image: registry.registry.svc.cluster.local:5000/oblivion@sha256:acd8c3da1acdc4c1f2c060c7dc7af416c52da6e46683382fdb5ace03ce589701
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - -m
            - oblivion
            - start
            - ubuild

