apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kube-system
  namespace: kube-system
spec:
  method: kubernetes
  mount: kubernetes-staging
  kubernetes:
    role: vault-secrets-operator-controller-manager
    serviceAccount: default
    audiences:
      - vault

