apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: argo-events
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system

