apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-events
  namespace: argo-events
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: argo-events
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system

