apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator-system
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: vault-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    defaultVaultConnection:
      enabled: true
      address: "https://10.8.0.3:8200"
      skipTLSVerify: true
    manager:
      logging:
        level: debug
    controller:
      clientCache:
        persistenceModel: none

