- name: Configure FRR BGP using mesh metadata from Redis
  hosts: all
  gather_facts: false
  vars:
    bgpd_conf_path: "/etc/frr/bgpd.conf"

  tasks:
    - name: Ensure FRR is installed
      ansible.builtin.apt:
        name:
          - frr
          - frr-pythontools
        state: present
        update_cache: true
      become: true

    - name: Enable bgpd daemon in FRR config
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: '^bgpd='
        line: 'bgpd=yes'
      become: true

    - name: Ensure FRR is started and enabled
      ansible.builtin.service:
        name: frr
        state: started
        enabled: true
      become: true

    - name: Fetch mesh peer metadata from Redis (via Python)
      ansible.builtin.command: python3 scripts/fetch_peer_data.py
      register: peer_json
      changed_when: false
      failed_when: peer_json.rc != 0

    - name: Parse JSON from peer metadata script
      set_fact:
        bgp_context: "{{ peer_json.stdout | from_json }}"

    - name: Render bgpd.conf from Jinja2 template
      ansible.builtin.template:
        src: "templates/bgpd.conf.j2"
        dest: "{{ bgpd_conf_path }}"
        owner: frr
        group: frr
        mode: "0644"
      vars:
        this_host: "{{ bgp_context.self }}"
        peers: "{{ bgp_context.peers }}"
      become: true

    - name: Restart FRR
      ansible.builtin.service:
        name: frr
        state: restarted
      become: true

