- name: Configure BIRD routing
  hosts: all
  vars:
    wireguard_peers_prefix: "wireguard:peers"
    bird_conf_path: "/etc/bird/bird.conf"

  tasks:
    - name: Install BIRD
      apt:
        name: bird2
        state: present
        update_cache: true

    - name: Load peer data from Redis
      command: python3 scripts/fetch_peer_data.py
      register: peer_json
      changed_when: false
      failed_when: peer_json.rc != 0

    - name: Parse peer info
      set_fact:
        peer_data: "{{ peer_json.stdout | from_json }}"

    - name: Ensure /etc/bird exists
      file:
        path: /etc/bird
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Template BIRD config
      template:
        src: "templates/bird.conf.j2"
        dest: "{{ bird_conf_path }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        this_host: "{{ peer_data.self }}"
        peers: "{{ peer_data.peers }}"

    - name: Restart BIRD
      service:
        name: bird
        state: restarted

