- name: Configure FRR using unified frr.conf from mesh metadata
  hosts: all
  vars:
    frr_conf_path: "/etc/frr/frr.conf"

  tasks:
    - name: Ensure FRR is installed
      ansible.builtin.apt:
        name:
          - frr
          - frr-pythontools
        state: present
        update_cache: true

    - name: Enable bgpd in FRR daemon config
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: '^bgpd='
        line: 'bgpd=yes'

    - name: Start and enable FRR service
      ansible.builtin.service:
        name: frr
        state: started
        enabled: true

    - name: Run Python script to get mesh peer info from Redis
      ansible.builtin.command: python3 scripts/fetch_peer_data.py
      register: peer_json
      changed_when: false
      failed_when: peer_json.rc != 0

    - name: Parse JSON peer info
      set_fact:
        bgp_context: "{{ peer_json.stdout | from_json }}"

    - name: Template unified frr.conf
      ansible.builtin.template:
        src: templates/frr.conf.j2
        dest: "{{ frr_conf_path }}"
        owner: frr
        group: frr
        mode: "0644"
      vars:
        this_host: "{{ bgp_context.self }}"
        peers: "{{ bgp_context.peers }}"

    - name: Restart FRR to apply config
      ansible.builtin.service:
        name: frr
        state: restarted

