- name: Installing Dokku role
  hosts: all
  tasks:
    - name: Install role at specific path
      community.general.ansible_galaxy_install:
        type: role
        name: dokku_bot.ansible_dokku
        dest: /root/.ansible/roles

