- name: Upgrade system packages
  hosts: all
  gather_facts: false

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages (non-interactive)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible after system upgrade"
        reboot_timeout: 300
      when: reboot_required.stat.exists

