- name: Developer Shell Setup
  hosts: all
  become: true
  vars:
    packages:
      - zsh
      - vim
      - git
      - curl
      - wget
      - bat
      - fd-find

  tasks:
    - name: Install common CLI tools
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes

    - name: Set vim as the default editor
      lineinfile:
        path: /etc/environment
        line: "EDITOR=vim"
        create: yes
        state: present

    - name: Set ZSH as the default shell for the user
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Clone oh-my-zsh
      become: false
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
        update: no

    - name: Copy default .zshrc
      become: false
      copy:
        src: "{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        force: no

    - name: Create symlink for bat
      file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
      when: ansible_facts.packages['bat'] is defined

