- name: Set up ZSH dev environment
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - zsh
          - vim
          - bat
          - fd-find
          - git
          - curl
        update_cache: yes
        state: present

    - name: Ensure oh-my-zsh is installed for the user
      become: false
      environment:
        HOME: "{{ ansible_env.HOME }}"
      shell: |
        if [ ! -d "{{ ansible_env.HOME }}/.oh-my-zsh" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        fi
      args:
        executable: /bin/bash

    - name: Set vim as the default editor
      lineinfile:
        path: /etc/environment
        line: "EDITOR=vim"
        create: yes
        state: present

    - name: Set ZSH as the default shell for the user
      user:
        name: "{{ ansible_facts.user_id }}"
        shell: /usr/bin/zsh

    - name: Make sure ~/.zshrc exists
      become: false
      file:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: touch
        mode: '0644'

