apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  values:
    serviceAccount:
      create: true
      name: reflector

