apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  namespace: crossplane-system
  name: provider-digitalocean
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-upjet-digitalocean:v0.3.0
  runtimeConfigRef:
    name: set-serviceaccount
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: set-serviceaccount
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane
