apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  namespace: crossplane-system
  name: provider-digitalocean
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-upjet-digitalocean:v0.3.0
