apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-staging

  # path of the secret
  path: apps/crossplane/cloud

  # dest k8s secret
  destination:
    name: crossplane
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: crossplane

