apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  method: kubernetes
  mount: kubernetes-staging
  kubernetes:
    role: vault-secrets-operator-controller-manager
    serviceAccount: crossplane
    audiences:
      - vault

