- name: Installing PowerDNS
  hosts: all
  vars:
    loglevel: 7
    server_local_port: 5300
    recursor_local_port: 53
    recursor_ip: "127.0.0.1"
    forward_zones:
      - "cluster.local=10.43.0.18:53"
      - "lan=127.0.0.1:5300"
    allow_from:
      - "127.0.0.1"
      - "10.0.0.0/8"
    local_address:
      - "{{ wireguard_ip }}"
      - "127.0.0.1"
    nameservers:
      - "127.0.0.1"
  tasks:
  - name: Get WireGuard details in JSON
    command: ip -j addr show wg0
    register: wg_json
    changed_when: false

  - name: Extract WireGuard IPv4 address
    set_fact:
      wireguard_ip: >-
        {{
          (wg_json.stdout | from_json)[0].addr_info
          | selectattr('family', 'equalto', 'inet')
          | map(attribute='local')
          | list
          | first
        }}

  - name: Debug WireGuard IP
    debug:
      msg: "WireGuard IP is {{ wireguard_ip }}"

  - name: Install PowerDNS
    apt:
      name: pdns-server
      update_cache: yes

  - name: Install PowerDNS Backend
    apt:
      name: pdns-backend-sqlite3
      update_cache: yes

  - name: Install PowerDNS Recursor
    apt:
      name: pdns-recursor
      update_cache: yes

  - name: Configure PowerDNS
    template:
      src: templates/pdns.conf.j2
      dest: /etc/powerdns/pdns.conf
    notify: Restart PowerDNS

  - name: Configure Recursor
    template:
      src: templates/pdns-recursor.conf.j2
      dest: /etc/powerdns/recursor.conf
    notify: Restart Recursor

  - name: Disable systemd-resolved
    systemd_service:
      name: systemd-resolved
      state: stopped
      enabled: false

  - name: Delete /etc/resolve.conf
    file:
      path: /etc/resolve.conf
      state: absent

  - name: Set up /etc/resolv.conf
    template:
      src: templates/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root

  handlers:
    - name: Restart PowerDNS
      service:
        name: pdns
        state: restarted

    - name: Restart Recursor
      service:
        name: pdns-recursor
        state: restarted
