apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  install:
    disableWait: true
    createNamespace: true
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    serviceAccount:
      enable: true
      name: open-webui
    ollama:
      enabled: false
    pipelines:
      enabled: false
    websocket:
      enabled: true
    enableOpenaiApi: true
    extraEnvVars:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: openai
            key: token


