apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openai
  namespace: open-webui
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-development

  # path of the secret
  path: apps/open-webui/openai

  # dest k8s secret
  destination:
    name: openai
    create: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "oblivion"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "oblivion"
  refreshAfter: 30s
  vaultAuthRef: open-webui

