apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: token-reviewer-binding
subjects:
  - kind: ServiceAccount
    name: token-reviewer
    namespace: oblivion
roleRef:
  kind: ClusterRole
  name: token-reviewer
  apiGroup: rbac.authorization.k8s.io

