apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-system
  namespace: cnpg-system
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-staging

  # path of the secret
  path: apps/cnpg-system

  # dest k8s secret
  destination:
    name: openai
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: cnpg-system

