apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-system
  namespace: cnpg-system
spec:
  type: kv-v2

  # mount path
  mount: kubernetes-development

  # path of the secret
  path: apps/cpng-system

  destination:
    name: cpng
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: cnpg-system

