apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cnpg-system
  namespace: cnpg-system
spec:
  method: kubernetes
  mount: kubernetes-development
  kubernetes:
    role: vault-secrets-operator-controller-manager
    serviceAccount: cnpg-manager
    audiences:
      - vault

