apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: certificates/oblivion-ca-certificate.yaml
  - path: cronjob.yaml
    target:
      group: batch
      version: v1
      name: bao-update-kubernetes-backend

