apiVersion: v1
data:
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICBzCCAY6gAwIBAgIUZXJHZ92OTtI7HW60KrTVS4Ei45IwCgYIKoZIzj0EAwMw
    OzELMAkGA1UEBhMCTkwxETAPBgNVBAoMCE9CTElWSU9OMRkwFwYDVQQDDBBPQkxJ
    VklPTiBST09UIENBMB4XDTI1MDQxMDIxMDAzN1oXDTM1MDQwODIxMDUzN1owOzEL
    MAkGA1UEBhMCTkwxETAPBgNVBAoMCE9CTElWSU9OMRkwFwYDVQQDDBBPQkxJVklP
    TiBST09UIENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEh9dt9gJ2164YflyCox2p
    QLxQLQ1H64ms52tKzqR1hMUe4lxsKKPCKxTCVpO4SDScSMQ7bO6AzvEvTFqrSydZ
    Mdx2uu7MSOItO+dbdV6f4s/dRjiUDQO5RfuTc10MYAOgo1MwUTAPBgNVHRMBAf8E
    BTADAQH/MB0GA1UdDgQWBBS1337Vq2+c8wfquznj6545bWCKTjAfBgNVHSMEGDAW
    gBS1337Vq2+c8wfquznj6545bWCKTjAKBggqhkjOPQQDAwNnADBkAjAZx7vQLIhZ
    7Q0zvtShfksa36nF6uDqdsGXtwpGGRlCAzA6t9DcbB1025HrMJn4ftICMBdIildZ
    e0zZ9ffaZ4n7yJqYndTWG7+SncHjGzfsndssErIgLBgAUqmspGUDG82h5Q==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: oblivion-ca-certificate
  namespace: kube-system
